### ISSUE TITLE
Wiki is full of duplicated entries and broken links.

### ISSUE THREAD

**Issue by destenson** [ActiveState/code#13]
The last commit of the wiki left most of its pages chock full of duplicates and incorrect links. I cleaned it up some, but someone should probably write a proper script to generate those files instead of whatever bone-headed method was used last time.

**Comment by destenson** [comment]
I dunno how the hell to edit the wiki or pull request my changes.  If you care about the wiki not being all in shambles, just replace what's there with what's on my version: https://github.com/destenson/ActiveState--code/tree/wiki

**Comment by rawktron** [comment]
Thanks for the issue report - the bug in the auto-generation script has been fixed and wiki updated. Closing this issue.
