### ISSUE TITLE
get_rev_children() ?

### ISSUE THREAD

**Issue by castrodd** [ActiveState/code#15]
In recipe-579138.py, there is a get_rev_children method in the depth-first search. This method does not work on any of my editors/REPLs and there is no documentation on it anywhere. Is this a typo? Or is something missing?

**Comment by CrumbleZ** [comment]
Works in python 2.7 and python 3.5

The method is from the `Node` class and simply returns the childrens of a node.

Using the following code in the `main` method : 
```
root = make_test_tree()
print(root.get_rev_children())
```

produces the following output : 

```
[Node: [b2], Node: [b1], Node: [b0]]
```

which is correct, according to how the test tree is built.

**Comment by castrodd** [comment]
@CrumbleZ Would it be possible to see your entire script? When I run those two lines of code, I still get the same error message.

**Comment by CrumbleZ** [comment]
What is the error message you are getting ?
What editor are you using ?
How are you running your code ? (From within your editor, or manually from a terminal ?)
