### ISSUE TITLE
Undefined function in recipe-580746.py

### ISSUE THREAD

**Issue by joneugster** [ActiveState/code#22]
In recipe-580746.py class `TK_Table`, `make_autoscroll()` seems not to be defined.

Sorry if I'm wrong. I might add further infos when i looked into it.

**Comment by schneeammer** [comment]
Also the horizontal Scrollbar needs the argument `orient = HORIZONTAL`.

`from tkinter import HORIZONTAL` and then in line 825: `self._hbar=Scrollbar(self, orient=HORIZONTAL, takefocus=0, command=xview_command, **scrollbar_kwargs)`
