### ISSUE TITLE
Code does not run

### ISSUE THREAD

**Issue by CaspianA1** [ActiveState/code#57]
Running the code with python3 does not yield anything.

**Comment by PrithiPal** [comment]
@CaspianA1 , can you tell which receipt you are referring to?

**Comment by CaspianA1** [comment]
What do you mean by receipt?

**Comment by PrithiPal** [comment]
My bad, I meant recipe

**Comment by CaspianA1** [comment]
I'm sorry - I don't remember anymore. My bad.

**Comment by PrithiPal** [comment]
@CaspianA1 , then it is better to close the issue.
