### ISSUE TITLE
DOC: what does "b/w" mean?

### ISSUE THREAD

**Issue by keithbriggs** [ActiveState/code#72]
I don't understand this:

> Returns a list of points from (start, end] by ray tracing a line b/w the points.

**Comment by zoofood** [comment]
It is short-form for between, and honestly doesn't need to be so obscure. ;) I will change.

**Comment by keithbriggs** [comment]
Thanks - it's not a logical abbreviation, since it suggests that "between" is made up of the words "bet" and "ween", when really it's made up of "be" and "tween"!
