### ISSUE TITLE
dmake is not getting included in ActivePerl-5.28 windows build configuration

### ISSUE THREAD

**Issue by noorez** [ActiveState/code#73]
I added the package dmake to a fork of an ActivePerl-5.28 build configuration, however, it doesn't appear to exist at all in the installation directory C:\Perl64...

**Comment by GrahamStuart** [comment]
dmake is not a Perl module. It's only in CPAN because CPAN allows creative off-label applications of the module definition concept.

The Platform blacklists dmake because the CPAN/C-Compiler/make module installation process is not supported.

**Comment by noorez** [comment]
Okay, thanks!. I'll leave it at this then.
